# Generated by Django 4.1 on 2022-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, default="No name", max_length=50),
                ),
                ("body", models.TextField()),
                (
                    "role",
                    models.CharField(blank=True, default="No role", max_length=200),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("created",),
            },
        ),
    ]
